# Generated by Django 5.1.2 on 2024-10-23 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Folder Name'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'parent', 'owner')},
        ),
    ]
