# Generated by Django 5.1.2 on 2024-10-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
