# Generated by Django 5.1.2 on 2024-10-25 21:50

import file_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0004_alter_file_extension_alter_file_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=file_management.models.user_directory_path),
        ),
    ]
