# Generated by Django 5.1.2 on 2024-10-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0005_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
